#!/bin/bash
if [ $# -lt 4 ]
  then
    echo "USAGE $0 source-file-or-directory workflow userid run-number [remainder-of-filespec]"
else
  src=$1
  if [ -r $src ]
    then

      dest="/mpo-storage/$2/$3/$4/$5"
      ssh  -i $HOME/.mporsync/id_rsa psfcmpo@psfcstor1 ls -Rl $dest
  fi
fi
