#!/bin/bash
if [ $# -lt 3 ]
  then
    echo "USAGE $0 workflow userid run-number [remainder-of-filespec]"
else
    src="psfcmpo@psfcstor1:/mpo-storage/$1/$2/$3/$4"
    rsync -av  -e "ssh  -i $HOME/.mporsync/id_rsa" $src .
fi
